name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2 Set Up Node.js 22
      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      # 3 Install and Build React Project
      - name: Install and Build React Project
        working-directory: src/main/app
        run: |
          npm install
          npm run build

      # 4. Set Up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      # 5. Cache Maven Dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 6. Build Maven Project
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 7. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/hotsse/busicard:latest .

      # 8. Push Docker Image to Docker Hub
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/hotsse/busicard:latest